### ISSUE TITLE
Hola, pregunta

### ISSUE THREAD

**Issue by TheLudway** [Junior-Jurado/parchelo#1]
Quiero poder armar parches para explotar capacitores, podría haber una opción para eso en específico?

Muchas gracias

**Comment by Junior-Jurado** [comment]
Gracias por tu sugerencia. Voy a discutirlo con los otros miembros de Parchelo y te aviso lo que decidamos. ¡Agradecemos que busques revolucionar Parchelo con ideas como esta!

**Comment by TheLudway** [comment]
Me alegra saber que todo el equipo escuchará mi solicitud, el equipo de Parchelo es lo mejor!

**Comment by Junior-Jurado** [comment]
Estimado Ludwig,

En nuestra plataforma, priorizamos la seguridad y el bienestar de nuestra comunidad. Por ello, después de un exhaustivo análisis, el equipo ha decidido que este tipo de eventos no será admitido en el aplicativo, por el momento, a futuro tal vez sí.

Esta decisión responde a nuestro compromiso con la protección integral de todos los usuarios, dado que la naturaleza de estos eventos podría implicar riesgos de lesiones o situaciones que comprometan la seguridad de las personas involucradas. Consideramos fundamental mantener un entorno seguro, responsable y alineado con nuestros principios de integridad.

Agradecemos su comprensión y colaboración en este esfuerzo conjunto por salvaguardar la experiencia positiva y segura dentro de nuestra plataforma. Para cualquier duda o aclaración adicional, no dude en contactarnos a través de los canales de soporte habituales.

Atentamente,
Equipo de parchelo

**Comment by TheLudway** [comment]
Muchas gracias por la respuesta, la considero muy apropiada y respetuosa. Aunque me pareció muy generada por ChatGPT, como que no hay un componente humano. Sinceramente, me pareció que la respondió un robot. Si así son respondiendo Issues, no quiero imaginar cómo son codificando historias de usuario.

Éxitos y mis mejores deseos en el desarrollo

_-Ludwig, Semi-Saint In The Church Of Emacs_

![semi-saint-button](https://github.com/user-attachments/assets/798f798e-54b9-4f0c-90a4-5c9b8ffb238a)

**Comment by Junior-Jurado** [comment]
Hola Ludwig Alvarado habla con Germán Jurado desde el equipo de Parchelo revisamos a detalle tu solicitud, un cofundador dio respuesta con cortesía a su petición, lo que yo le puedo decir es que Parchelo no discrimina a nadie, por lo que, podrás crear eventos de todo lo que quieras ya que Parchelo trasciende fronteras. 

Lo que me parece ilógico de su parte que venga con comentarios fuera de lugar cuando hasta hora Parchelo esta en sus cimientos, fuiste elegido para retroalimentar la app pero debido a que no te encuentras augusto serás relevado de dicha carga.

Agradecemos tu tiempo en hacer de Parchelo un sueño a una realidad.

**Comment by TheLudway** [comment]
Valevale, yo lo entiendo, pero uno intenta hacer parches divertidos como explotar capacitores (algo muy exótico) y resulta que no se puede. Después me llega sumercé diciendo que sí se van a poder hacer parches de lo que quiera, entonces encuentro que no hay una comunicación clara entre el equipo... Estos son los profesionales que saca la Jorge Tadeo Lozano? No estoy siendo grosero, nomás estoy viendo incongruencias en tan sólo la planeación del proyecto. Encima, he seguido la planeación en algunas reuniones y están utilizando Google Docs, por qué? Qué clase de profesionales salen hoy en día... En fin, éxitos con el proyecto, no pienso a volver por estos sitios.

Muchas gracias por la respuesta.

_-Ludwig, Semi-Saint In The Church Of Emacs_

![semi-saint-button](https://github.com/user-attachments/assets/798f798e-54b9-4f0c-90a4-5c9b8ffb238a)

**Comment by Junior-Jurado** [comment]
Estimado Ludwig desde el equipo Parchelo, lamentamos sus palabras no esperábamos que tuvieras esta reacción, es una pena que no haga parte de la comunidad de Parchelo.

Nos parece un poco equivocada su respuesta ya que en el mensaje aclaramos que en el futuro se van a hacer posible estos eventos ya que vamos a iniciar con eventos de un alcance global para ir poco a poco con los que convoca menos relevancia, por ejemplo, sabemos que te gusta poguear ese sería primero antes de estallar capacitores. 

Con respecto a la educación creo que estas juzgando tanto a la universidad como al equipo de desarrollo, lastimosamente esto va en contra de nuestros valores por lo que quedaste vetado de la comunidad hasta que se presente una disculpa formal. 

Este es el último mensaje contestado por parte de Parchelo, de ahora en adelante sus mensajes serán ignorados.

Gracias por hacer de Parchelo un sueño a una realidad
